[package]
name = "madness-battlegrounds"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
# bevy_flycam = "0.13.0"
bevy-inspector-egui = "0.25.0"
bevy_sprite3d = "3.0.0"
pathfinding = "4.3.0"
futures-lite = "*"
num = "*"
vleue_navigator = "0.8.0"